const title = 'Java Script course';
let screens = ("Простые,Сложные,Интерактивные");
const screensArray = screens.toLowerCase().split(" ");
const screenPrice = 200;
const rollback = 24;
const fullPrice = 30000;
const adaptive = true;
console.log(typeof(title));
console.log(typeof(fullPrice));
console.log(typeof(adaptive));
console.log(screens.length);
console.log("Стоимость верстки экранов"+ " " + screenPrice + " " + "долларов");
console.log("Стоимость разработки сайта"+ " " + fullPrice + " " + "долларов");
console.log(screensArray);
console.log(fullPrice * (rollback/100));